title: Project
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  year:
    label: Year
    type: text
    width: 1/2
  category:
    label: Category
    type: text
    width: 1/2
  text:
    label: Text
    type:  textarea
